server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d0bmd1muk2gs73fvsjg0-a:5432/furia_3uue
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

websocket:
  endpoint: /ws
  destination-prefix: /topic
  application-prefix: /app